version: "0.0.5"
services:
  sssd:
    image: egpivo/sssd:latest
    volumes:
      - ./datasets/:/sssd/datasets
      - ./config/:/sssd/config
      - ./results:/sssd/results
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      CONFIG_FILE: "config_SSSDS4-NYISO-3-mix.json"  # Specify the new config file here
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
