version: "0.0.3"
services:
  sssd:
    build:
      dockerfile: envs/docker/Dockerfile
    volumes:
      - ./datasets/:/home/worker/sssd/datasets
      - ./config/:/home/worker/sssd/config
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      CONFIG_FILE: "config_SSSDS4-NYISO-3-mix.json"  # Specify the new config file here
