wavenet:
  # WaveNet model parameters
  in_channels: 1  # Number of input channels
  out_channels: 1  # Number of output channels
  res_layers: 2  # Number of residual layers
  res_channels: 2  # Number of channels in residual blocks
  skip_channels: 2  # Number of channels in skip connections

  # Diffusion step embedding dimensions
  diffusion_step_embed_dim_in: 128  # Input dimension
  diffusion_step_embed_dim_mid: 512  # Middle dimension
  diffusion_step_embed_dim_out: 512  # Output dimension

  # Structural State-Space Model (S4) configurations
  s4_max_seq_len: 200  # Maximum sequence length
  s4_state_dim: 64  # State dimension
  s4_dropout: 0.0  # Dropout rate
  s4_bidirectional: true  # Whether to use bidirectional layers
  s4_use_layer_norm: true  # Whether to use layer normalization

diffusion:
  # Diffusion model parameters
  num_steps: 200  # Number of diffusion steps
  beta_start: 0.0001  # Initial beta value
  beta_end: 0.02  # Final beta value
