
# configs/training.yaml
# Training configuration
batch_size: 80  # Batch size
output_dir: "./results/experiment"  # Output directory for checkpoints and logs
ckpt_mode: "max"  # Checkpoint mode (max or min)
ckpt_freq: 1  # Checkpoint frequency (number of epochs)
log_freq: 1  # Log frequency (number of iterations)
max_iters: 5  # Maximum number of iterations
learning_rate: 2e-4  # Learning rate

# Additional training settings
generate_missing_only: true  # Generate missing values only
model_to_use: 2  # Model to use for training
masking_strategy: "forecast"  # Masking strategy for missing values
missing_values: 24  # Number of missing values

# Data paths
data:
  train_path: "./datasets/experiment/train_data.npy"  # Path to training data
